moonmining/urls.py
"""Routes."""

from django.urls import path

from moonmining.views import extractions, moons, reports

from .views import general

app_name = "moonmining"

urlpatterns = [
    # general
    path("", general.index, name="index"),
    path("add_owner", general.add_owner, name="add_owner"),
    path("modal_loader_body", general.modal_loader_body, name="modal_loader_body"),
    path("tests", general.tests, name="tests"),
    # extractions
    path("extractions", extractions.extractions, name="extractions"),
    path(
        "extractions_data/<str:category>",
        extractions.extractions_data,
        name="extractions_data",
    ),
    path(
        "extraction/<int:extraction_pk>",
        extractions.extraction_details,
        name="extraction_details",
    ),
    path(
        "extraction_ledger/<int:extraction_pk>",
        extractions.extraction_ledger,
        name="extraction_ledger",
    ),
    # moons
    path("moons", moons.moons, name="moons"),
    path("upload_survey", moons.upload_survey, name="upload_survey"),
    path(
        "moons_data/<str:category>",
        moons.MoonListJson.as_view(),
        name="moons_data",
    ),
    path(
        "moons_fdd_data/<str:category>",
        moons.moons_fdd_data,
        name="moons_fdd_data",
    ),
    path("moon/<int:moon_pk>", moons.moon_details, name="moon_details"),
    # reports
    path("reports", reports.reports, name="reports"),
    path(
        "report_owned_value_data",
        reports.report_owned_value_data,
        name="report_owned_value_data",
    ),
    path(
        "report_user_mining_data",
        reports.report_user_mining_data,
        name="report_user_mining_data",
    ),
    path(
        "report_user_uploaded_data",
        reports.report_user_uploaded_data,
        name="report_user_uploaded_data",
    ),
    path(
        "report_ore_prices_data",
        reports.report_ore_prices_data,
        name="report_ore_prices_data",
    ),
]

moonmining/views/extractions.py
"""Extraction views."""

import datetime as dt
from enum import Enum

from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import (
    ExpressionWrapper,
    F,
    FloatField,
    IntegerField,
    QuerySet,
    Sum,
    Value,
)
from django.db.models.functions import Coalesce
from django.http import HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.html import format_html
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from allianceauth.eveonline.evelinks import dotlan
from app_utils.views import fontawesome_modal_button_html, link_html, yesno_str

from moonmining import helpers
from moonmining.app_settings import (
    MOONMINING_COMPLETED_EXTRACTIONS_HOURS_UNTIL_STALE,
    MOONMINING_REPROCESSING_YIELD,
    MOONMINING_USE_REPROCESS_PRICING,
    MOONMINING_VOLUME_PER_MONTH,
)
from moonmining.constants import DATE_FORMAT, DATETIME_FORMAT
from moonmining.models import Extraction
from moonmining.views._helpers import moon_details_button_html


class ExtractionsCategory(str, helpers.EnumToDict, Enum):
    """A category defining which extractions to show in data view."""

    UPCOMING = "upcoming"
    PAST = "past"


@login_required
@permission_required(["moonmining.extractions_access", "moonmining.basic_access"])
def extractions(request):
    """Render extractions page."""
    context = {
        "page_title": _("Extractions"),
        "ExtractionsCategory": ExtractionsCategory.to_dict(),
        "ExtractionsStatus": Extraction.Status,
        "use_reprocess_pricing": MOONMINING_USE_REPROCESS_PRICING,
        "reprocessing_yield": MOONMINING_REPROCESSING_YIELD * 100,
        "total_volume_per_month": MOONMINING_VOLUME_PER_MONTH / 1000000,
        "stale_hours": MOONMINING_COMPLETED_EXTRACTIONS_HOURS_UNTIL_STALE,
    }
    return render(request, "moonmining/extractions.html", context)


def extraction_ledger_button_html(extraction: Extraction) -> str:
    """Return HTML to render extraction ledger button."""
    new_var = fontawesome_modal_button_html(
        modal_id="modalExtractionLedger",
        fa_code="fas fa-table",
        ajax_url=reverse("moonmining:extraction_ledger", args=[extraction.pk]),
        tooltip="Extraction ledger",
    )
    return new_var


def extraction_details_button_html(extraction_pk: int) -> str:
    """Return HTML to render extraction details button."""
    html = fontawesome_modal_button_html(
        modal_id="modalExtractionDetails",
        fa_code="fas fa-hammer",
        ajax_url=reverse("moonmining:extraction_details", args=[extraction_pk]),
        tooltip=_("Extraction details"),
    )
    return html


@login_required
@permission_required(["moonmining.extractions_access", "moonmining.basic_access"])
def extractions_data(request: HttpRequest, category: str):
    """Render extraction data."""
    data = []
    can_see_ledger = request.user.has_perm("moonmining.view_moon_ledgers")
    extractions_qs = _calc_extractions_qs(ExtractionsCategory(category))
    for extraction in extractions_qs:
        moon = extraction.refinery.moon
        moon_name = str(moon)
        refinery_name = str(extraction.refinery.name)
        solar_system = moon.eve_moon.eve_planet.eve_solar_system
        location = format_html(
            "{}<br><i>{}</i>",
            link_html(dotlan.solar_system_url(solar_system.name), moon_name),
            solar_system.eve_constellation.eve_region.name,
        )

        if (
            extraction.status == Extraction.Status.COMPLETED
            and extraction.ledger.exists()
        ):
            mined_value = extraction.ledger.aggregate(Sum(F("total_price")))[
                "total_price__sum"
            ]
            actions_html = (
                extraction_ledger_button_html(extraction) + "&nbsp;"
                if can_see_ledger
                else ""
            )
        else:
            actions_html = ""
            mined_value = None

        actions_html += extraction_details_button_html(extraction.pk)
        actions_html += "&nbsp;" + moon_details_button_html(extraction.refinery.moon)
        status_html = format_html(
            "{}<br>{}",
            extraction.chunk_arrival_at.strftime(DATETIME_FORMAT),
            extraction.status_enum.bootstrap_tag_html,
        )
        data.append(
            {
                "id": extraction.pk,
                "chunk_arrival_at": {
                    "display": status_html,
                    "sort": extraction.chunk_arrival_at,
                },
                "refinery": {
                    "display": extraction.refinery.name_html(),
                    "sort": refinery_name,
                },
                "location": {
                    "display": location,
                    "sort": moon_name,
                },
                "labels": moon.labels_html(),
                "volume": extraction.volume,
                "value": extraction.value if extraction.value else None,
                "mined_value": mined_value,
                "details": actions_html,
                "corporation_name": extraction.refinery.owner.name,
                "alliance_name": extraction.refinery.owner.alliance_name,
                "moon_name": moon_name,
                "region_name": solar_system.eve_constellation.eve_region.name,
                "constellation_name": solar_system.eve_constellation.name,
                "rarity_class": moon.get_rarity_class_display(),
                "is_jackpot_str": yesno_str(extraction.is_jackpot),
                "is_ready": extraction.chunk_arrival_at <= now(),
                "status": extraction.status,
                "status_str": Extraction.Status(extraction.status).label,
            }
        )
    return JsonResponse(data, safe=False)


def _calc_extractions_qs(category: ExtractionsCategory) -> QuerySet[Extraction]:
    stale_cutoff = now() - dt.timedelta(
        hours=MOONMINING_COMPLETED_EXTRACTIONS_HOURS_UNTIL_STALE
    )
    extractions_qs = (
        Extraction.objects.annotate_volume()
        .selected_related_defaults()
        .select_related(
            "refinery__moon__eve_moon__eve_planet__eve_solar_system",
            "refinery__moon__eve_moon__eve_planet__eve_solar_system__eve_constellation",
            "refinery__moon__eve_moon__eve_planet__eve_solar_system__eve_constellation__eve_region",
        )
    )
    if category is ExtractionsCategory.UPCOMING:
        extractions_qs = extractions_qs.filter(
            auto_fracture_at__gte=stale_cutoff
        ).exclude(status=Extraction.Status.CANCELED)

    elif category is ExtractionsCategory.PAST:
        extractions_qs = extractions_qs.filter(
            auto_fracture_at__lt=stale_cutoff
        ) | extractions_qs.filter(status=Extraction.Status.CANCELED)

    else:
        extractions_qs = Extraction.objects.none()
    return extractions_qs


@login_required
@permission_required(["moonmining.extractions_access", "moonmining.basic_access"])
def extraction_details(request, extraction_pk: int):
    """Render a details view for an extraction."""
    extraction = get_object_or_404(
        Extraction.objects.annotate_volume().select_related(
            "refinery",
            "refinery__moon",
            "refinery__moon__eve_moon",
            "refinery__moon__eve_moon__eve_planet__eve_solar_system",
            "refinery__moon__eve_moon__eve_planet__eve_solar_system__eve_constellation__eve_region",
            "canceled_by",
            "fractured_by",
            "started_by",
        ),
        pk=extraction_pk,
    )
    context = {
        "page_title": (
            f"{extraction.refinery.moon} "
            f"| {extraction.chunk_arrival_at.strftime(DATE_FORMAT)}"
        ),
        "extraction": extraction,
    }
    if request.GET.get("new_page"):
        context["title"] = _("Extraction")
        context["content_file"] = "moonmining/partials/extraction_details.html"
        return render(request, "moonmining/_generic_modal_page.html", context)

    return render(request, "moonmining/modals/extraction_details.html", context)


@login_required
@permission_required(
    [
        "moonmining.extractions_access",
        "moonmining.basic_access",
        "moonmining.view_moon_ledgers",
    ]
)
def extraction_ledger(request, extraction_pk: int):
    """Render extraction ledger page."""
    extraction = get_object_or_404(
        Extraction.objects.all().select_related(
            "refinery",
            "refinery__moon",
            "refinery__moon__eve_moon__eve_planet__eve_solar_system",
            "refinery__moon__eve_moon__eve_planet__eve_solar_system__eve_constellation__eve_region",
        ),
        pk=extraction_pk,
    )
    ledger = extraction.ledger.select_related(
        "character", "corporation", "user__profile__main_character", "ore_type"
    )
    total_value = ledger.aggregate(Sum(F("total_price")))["total_price__sum"]
    total_volume = ledger.aggregate(Sum(F("total_volume")))["total_volume__sum"]
    sum_price = ExpressionWrapper(
        F("quantity") * Coalesce(F("unit_price"), 0), output_field=FloatField()
    )
    sum_volume = ExpressionWrapper(
        F("quantity") * F("ore_type__volume"), output_field=IntegerField()
    )
    character_totals = (
        ledger.values(
            character_name=F("character__name"),
            main_name=F("user__profile__main_character__character_name"),
            corporation_name=F("user__profile__main_character__corporation_name"),
        )
        .annotate(character_total_price=Sum(sum_price, distinct=True))
        .annotate(character_total_volume=Sum(sum_volume, distinct=True))
        .annotate(
            character_percent_value=ExpressionWrapper(
                F("character_total_price") / Value(total_value) * Value(100),
                output_field=IntegerField(),
            )
        )
        .annotate(

moonmining/templates/moonmining/_generic_modal_page.html
{% extends 'moonmining/base.html' %}
{% load i18n %}
{% load static %}

{% block details %}
    <div class="panel panel-default" style="max-width:900px;">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">{% include content_file %}</div>
    </div>
{% endblock %}

moonmining/templates/moonmining/moons.html
{% extends 'moonmining/base.html' %}
{% load i18n %}
{% load static %}

{% block details %}
    <span class="pull-right">
        {% if perms.moonmining.upload_moon_scan %}
            <button type="button" class="btn btn-success btn-tabs" data-toggle="modal" data-target="#modalUploadSurvey" data-ajax_url="{% url 'moonmining:upload_survey' %}">
                {% translate "Upload Moon Surveys" %}
            </button>
        {% endif %}
    </span>

    <!-- Nav tabs -->
    <ul id="myTabs" class="nav nav-tabs" role="tablist">
        {% if perms.moonmining.extractions_access or perms.moonmining.view_all_moons %}
            <li role="presentation">
                <a href="#tab_{{ MoonsCategory.OURS }}" aria-controls="tab_{{ MoonsCategory.OURS }}" role="tab" data-toggle="tab">{% translate "Owned Moons" %}</a>
            </li>
        {% endif %}
        {% if perms.moonmining.view_all_moons %}
            <li role="presentation">
                <a href="#tab_{{ MoonsCategory.ALL }}" aria-controls="tab_{{ MoonsCategory.ALL }}" role="tab" data-toggle="tab">{% translate "All Moons" %}</a>
            </li>
        {% endif %}
        {% if perms.moonmining.upload_moon_scan %}
            <li role="presentation">
                <a href="#tab_{{ MoonsCategory.UPLOADS }}" aria-controls="tab_{{ MoonsCategory.UPLOADS }}" role="tab" data-toggle="tab">{% translate "My Uploaded Moons" %}</a>
            </li>
         {% endif %}
    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">
                {% include "moonmining/partials/moons_tab.html" with category=MoonsCategory.OURS %}
                {% include "moonmining/partials/moons_tab.html" with category=MoonsCategory.ALL %}
                {% include "moonmining/partials/moons_tab.html" with category=MoonsCategory.UPLOADS %}
            </div>
            {% include 'moonmining/partials/value_estimate_legend.html' %}
        </div>
    </div>

    {% if perms.moonmining.extractions_access or perms.moonmining.view_all_moons %}
        <script>var defaultTab = "tab_{{MoonsCategory.OURS}}";</script>
    {% elif perms.moonmining.upload_moon_scan %}
        <script>var defaultTab = "tab_{{MoonsCategory.UPLOADS}}";</script>
    {% endif %}

    {{ user_perms|json_script:"user-perms" }}

    <!-- Modals -->
    {% include "moonmining/modals/base.html" with modal_id="modalUploadSurvey" modal_content_id="modalUploadSurveyContent" %}
    {% include "moonmining/modals/base.html" with modal_id="modalMoonDetails" modal_content_id="modalMoonDetailsContent" %}
    {% include "moonmining/modals/base.html" with modal_id="modalExtractionDetails" modal_content_id="modalExtractionDetailsContent" %}
{% endblock %}

{% block extra_javascript %}
    {{ block.super }}
    <script type="text/javascript">
        "use_strict";
        const perms = JSON.parse(document.getElementById('user-perms').textContent);
        $(function(){
            let dropDownColumns = [
                {
                    idx: 10,
                    title: "{% translate 'Alliance' %}",
                    maxWidth: "10em"
                },
                {
                    idx: 9,
                    title: "{% translate 'Corporation' %}",
                    maxWidth: "10em"
                },
                {
                    idx: 15,
                    title: "{% translate 'Region' %}",
                    maxWidth: "10em"
                },
                {
                    idx: 13,
                    title: "{% translate 'Constellation' %}",
                    maxWidth: "10em"
                },
                {
                    idx: 7,
                    title: "{% translate 'System' %}",
                    maxWidth: "10em"
                },
                {
                    idx: 11,
                    title: "{% translate 'Rarity' %}",
                    maxWidth: "10em"
                },
                {
                    idx: 14,
                    title: "{% translate 'Label' %}",
                    maxWidth: "10em"
                },
                {
                    idx: 8,
                    title: "{% translate 'Owned?' %}",
                    maxWidth: "10em"
                }
            ];
            if (perms.moonmining.extractions_access) {
                dropDownColumns.push({
                    idx: 12,
                    title: "{% translate 'Extraction?' %}",
                    maxWidth: "10em"
                });
            }
            const def = {
                ajax: {
                    url: '',
                    dataSrc: 'data',
                    cache: true
                },
                columns: [
                    { data: 'moon_name' },
                    { data: 'solar_system_link' },
                    { data: 'location_html' },
                    { data: 'refinery',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'labels'},
                    {
                        data: 'value',
                        render: $.fn.dataTable.render.formatisk()
                    },
                    { data: 'details' },
                    /* hidden columns */
                    { data: 'solar_system_name' },
                    { data: 'has_refinery_str' },
                    { data: 'corporation_name' },
                    { data: 'alliance_name' },
                    { data: 'rarity_class_str' },
                    { data: 'has_extraction_str' },
                    { data: 'constellation_name' },
                    { data: 'label_name' },
                    { data: 'region_name' },
                ],
                searching: true,
                processing: true,
                serverSide: true,
                lengthMenu: DEFAULT_LENGTH_MENU,
                pageLength: DEFAULT_PAGE_LENGTH,
                order: [ [0, "asc"] ],
                columnDefs: [
                    { "orderable": false, "targets": [ 4, 6 ] },
                    { "visible": false, "targets": [ 7, 8, 9, 10, 11, 12, 13, 14, 15 ] },
                ],
                filterDropDown: {
                    columns: dropDownColumns,
                    bootstrap: true,
                    autoSize: false
                }
            };

            /* our moons table */
            let def_ours = jQuery.extend(true, {}, def)
            def_ours.ajax.url = '{% url "moonmining:moons_data" MoonsCategory.OURS %}'
            def_ours.filterDropDown.ajax = '{% url "moonmining:moons_fdd_data" MoonsCategory.OURS %}'
            let table_our = $('#table_{{ MoonsCategory.OURS }}').DataTable(def_ours);
            table_our.on( 'init', function () {
                table_our.columns.adjust().draw();
                $("#loader_{{ MoonsCategory.OURS }}").hide();
                $("#wrapper_{{ MoonsCategory.OURS }}").show();
            } );

            /* all moons table */
            let def_all = jQuery.extend(true, {}, def)
            def_all.ajax.url = '{% url "moonmining:moons_data" MoonsCategory.ALL %}'
            def_all.filterDropDown.ajax = '{% url "moonmining:moons_fdd_data" MoonsCategory.ALL %}'
            let table_all = $('#table_{{ MoonsCategory.ALL }}').DataTable(def_all);
            table_all.on( 'init', function () {
                table_all.columns.adjust().draw();
                $("#loader_{{ MoonsCategory.ALL }}").hide();
                $("#wrapper_{{ MoonsCategory.ALL }}").show();
            } );

            /* uploaded moons table */
            let def_uploads = jQuery.extend(true, {}, def)
            def_uploads.ajax.url = '{% url "moonmining:moons_data" MoonsCategory.UPLOADS %}'
            def_uploads.filterDropDown.ajax = '{% url "moonmining:moons_fdd_data" MoonsCategory.UPLOADS %}'
            let table_uploads = $('#table_{{ MoonsCategory.UPLOADS }}').DataTable(def_uploads);
            table_uploads.on( 'init', function () {
                table_uploads.columns.adjust().draw();
                $("#loader_{{ MoonsCategory.UPLOADS }}").hide();
                $("#wrapper_{{ MoonsCategory.UPLOADS }}").show();
            } );

            $('#myTabs a[href="#' + defaultTab + '"]').tab('show');

            handle_modal_events("modalUploadSurvey", "modalUploadSurveyContent");
            handle_modal_events("modalMoonDetails", "modalMoonDetailsContent");
            handle_modal_events("modalExtractionDetails", "modalExtractionDetailsContent");

        });
    </script>
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{% static 'moonmining/css/moons.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block extra_script %}
{% endblock %}

moonmining/templates/moonmining/reports.html
{% extends 'moonmining/base.html' %}
{% load i18n %}
{% load static %}

{% block details %}
    <ul id="myTabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#tab_owned_value" aria-controls="tab_owned_value" role="tab" data-toggle="tab">Potential monthly income</a>
        </li>
        <li role="presentation">
            <a href="#tab_user_mining" aria-controls="tab_user_mining" role="tab" data-toggle="tab">Member Mining</a>
        </li>
        <li role="presentation">
            <a href="#tab_user_uploaded" aria-controls="tab_user_uploaded" role="tab" data-toggle="tab">Member Uploads</a>
        </li>
        <li role="presentation">
            <a href="#tab_ore_prices" aria-controls="tab_ore_prices" role="tab" data-toggle="tab">Ore prices</a>
        </li>
    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">
                {% include "moonmining/partials/reports_owned_value_tab.html" %}
                {% include "moonmining/partials/reports_user_mining_tab.html" %}
                {% include "moonmining/partials/reports_user_uploaded_tab.html" %}
                {% include "moonmining/partials/reports_ore_prices_tab.html" %}
            </div>
        </div>
    </div>


    <!-- Modals -->
    {% include "moonmining/modals/base.html" with modal_id="modalMoonDetails" modal_content_id="modalMoonDetailsContent" %}
{% endblock %}

{% block extra_javascript %}
    {{ block.super }}
    <script type="application/javascript" src="{% static 'moonmining/vendor/datatables/plugins/dataTables.rowGroup.min.js' %}"></script>
    <script type="text/javascript">
        "use_strict";
        $(function() {
            $('#table_owned_value').DataTable({
                ajax: {
                    url: '{% url "moonmining:report_owned_value_data" %}',
                    dataSrc: '',
                    cache: true
                },
                columns: [
                    { data: 'corporation' },
                    { data: 'moon',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'region' },
                    { data: 'rarity_class' },
                    {
                        data: 'value',
                        render: $.fn.dataTable.render.formatisk()
                    },
                    {
                        data: 'grand_total_percent',
                        render: $.fn.dataTable.render.number(',', '.', 0)
                    },
                    { data: 'rank' },
                    {
                        data: 'total',
                        render: $.fn.dataTable.render.formatisk()
                    },
                ],
                lengthMenu: DEFAULT_LENGTH_MENU,
                pageLength: DEFAULT_PAGE_LENGTH,
                order: [ [0, "asc"], [1, "asc"] ],
                ordering: false,
                rowGroup: {
                    dataSrc: 'corporation',
                    className: 'table-group'
                },
                columnDefs: [
                    { "visible": false, "targets": [ 0 ] },
                    { "orderable": false, "targets": [ 1 ] },
                ],
                createdRow: function( row, data, dataIndex ) {
                    if (data['is_total']) {
                        $(row).addClass('info');
                    }
                },
                footerCallback: function (row, data, start, end, display) {
                    const api = this.api();

                    dataTableFooterSumColumn(api, 5);
                    dataTableFooterSumColumn(api, 7, 'isk');
                }
            });

            $('#table_user_mining').DataTable({
                ajax: {
                    url: '{% url "moonmining:report_user_mining_data" %}',
                    dataSrc: '',
                    cache: true
                },
                columns: [
                    { data: 'name' },
                    { data: 'corporation' },
                    { data: 'state' },
                    {
                        data: 'volume_month_3',
                        render: $.fn.dataTable.render.number(',', '.', 0)
                    },
                    {
                        data: 'price_month_3',
                        render: $.fn.dataTable.render.formatisk()
                    },
                    {
                        data: 'volume_month_2',
                        render: $.fn.dataTable.render.number(',', '.', 0)
                    },
                    {
                        data: 'price_month_2',
                        render: $.fn.dataTable.render.formatisk()
                    },
                    {
                        data: 'volume_month_1',
                        render: $.fn.dataTable.render.number(',', '.', 0)
                    },
                    {
                        data: 'price_month_1',
                        render: $.fn.dataTable.render.formatisk()
                    },
                    {
                        data: 'volume_month_0',
                        render: $.fn.dataTable.render.number(',', '.', 0)
                    },
                      {
                        data: 'price_month_0',
                        render: $.fn.dataTable.render.formatisk()
                    }

                ],
                lengthMenu: DEFAULT_LENGTH_MENU,
                pageLength: DEFAULT_PAGE_LENGTH,
                order: [ [0, "asc"] ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 1,
                            title: "{% translate 'Corporation' %}"
                        },
                        {
                            idx: 2,
                            title: "{% translate 'State' %}"
                        }
                    ],
                    bootstrap: true,
                    autoSize: false
                },
                footerCallback: function (row, data, start, end, display) {
                    const api = this.api();

                    dataTableFooterSumColumn(api, 3);
                    dataTableFooterSumColumn(api, 4, 'isk');
                    dataTableFooterSumColumn(api, 5);
                    dataTableFooterSumColumn(api, 6, 'isk');
                    dataTableFooterSumColumn(api, 7);
                    dataTableFooterSumColumn(api, 8, 'isk');
                    dataTableFooterSumColumn(api, 9);
                    dataTableFooterSumColumn(api, 10, 'isk');
                }
            });

            $('#table_user_uploaded').DataTable({
                ajax: {
                    url: '{% url "moonmining:report_user_uploaded_data" %}',
                    dataSrc: '',
                    cache: true
                },
                columns: [
                    { data: 'name' },
                    { data: 'corporation' },
                    { data: 'state' },
                    {
                        data: 'num_moons',
                        render: $.fn.dataTable.render.number(',', '.', 0)
                    }
                ],
                lengthMenu: DEFAULT_LENGTH_MENU,
                pageLength: DEFAULT_PAGE_LENGTH,
                order: [ [0, "asc"] ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 1,
                            title: "{% translate 'Corporation' %}"
                        },
                        {
                            idx: 2,
                            title: "{% translate 'State' %}"
                        }
                    ],
                    bootstrap: true,
                    autoSize: false
                },
                footerCallback: function (row, data, start, end, display) {
                    dataTableFooterSumColumn(this.api(), 3);
                }
            });

            $('#table_ore_prices').DataTable({
                ajax: {
                    url: '{% url "moonmining:report_ore_prices_data" %}',
                    dataSrc: '',
                    cache: true
                },
                columns: [
                    { data: 'name' },
                    {
                        data: 'price',
                        render: $.fn.dataTable.render.number(',', '.', 2)
                    },
                    { data: 'group' },
                    {
                        data: 'rarity_html',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }

                    },
                    { data: 'description' },
                    { data: 'rarity_str' },
                ],
                lengthMenu: DEFAULT_LENGTH_MENU,
                pageLength: DEFAULT_PAGE_LENGTH,
                order: [ [0, "asc"] ],
                columnDefs: [
                    { "visible": false, "targets": [ 5 ] },
                ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 2
                        },
                        {
                            idx: 5,
                            title: "{% translate 'Rarity' %}"
                        }
                    ],
                    bootstrap: true,
                    autoSize: false
                }
            });

            handle_modal_events("modalMoonDetails", "modalMoonDetailsContent")
        });
    </script>
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'memberaudit/vendor/datatables/plugins/rowGroup.dataTables.min.css' %}" type="text/css">
    <link href="{% static 'moonmining/css/reports.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block extra_script %}
{% endblock %}