moonmining/urls.py
"""Routes."""

from django.urls import path

from moonmining.views import extractions, moons, reports

from .views import general

app_name = "moonmining"

urlpatterns = [
    # general
    path("", general.index, name="index"),
    path("add_owner", general.add_owner, name="add_owner"),
    path("modal_loader_body", general.modal_loader_body, name="modal_loader_body"),
    path("tests", general.tests, name="tests"),
    # extractions
    path("extractions", extractions.extractions, name="extractions"),
    path(
        "extractions_data/<str:category>",
        extractions.extractions_data,
        name="extractions_data",
    ),
    path(
        "extraction/<int:extraction_pk>",
        extractions.extraction_details,
        name="extraction_details",
    ),
    path(
        "extraction_ledger/<int:extraction_pk>",
        extractions.extraction_ledger,
        name="extraction_ledger",
    ),
    # moons
    path("moons", moons.moons, name="moons"),
    path("upload_survey", moons.upload_survey, name="upload_survey"),
    path(
        "moons_data/<str:category>",
        moons.MoonListJson.as_view(),
        name="moons_data",
    ),
    path(
        "moons_fdd_data/<str:category>",
        moons.moons_fdd_data,
        name="moons_fdd_data",
    ),
    path("moon/<int:moon_pk>", moons.moon_details, name="moon_details"),
    # reports
    path("reports", reports.reports, name="reports"),
    path(
        "report_owned_value_data",
        reports.report_owned_value_data,
        name="report_owned_value_data",
    ),
    path(
        "report_user_mining_data",
        reports.report_user_mining_data,
        name="report_user_mining_data",
    ),
    path(
        "report_user_uploaded_data",
        reports.report_user_uploaded_data,
        name="report_user_uploaded_data",
    ),
    path(
        "report_ore_prices_data",
        reports.report_ore_prices_data,
        name="report_ore_prices_data",
    ),
]

moonmining/templates/moonmining/modals/base.html
<!-- Base template for all modals. Creates a loader. -->

<div class="modal" id="{{ modal_id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    {% include "moonmining/modals/content_base.html" with modal_content_id=modal_content_id modal_body_url="moonmining/modals/loader_body.html" modal_title="Loading..." modal_size=modal_size %}
</div>

moonmining/templates/moonmining/modals/content_base.html
<!-- Base template for creating the HTML for a modal. -->

{% load i18n %}

<div class="modal-dialog {{ modal_size|default:'modal-lg' }}" role="document" id="{{ modal_content_id }}">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
                &times;
            </span></button>
            <h4 class="modal-title" id="myModalLabel">{{ modal_title }}</h4>
        </div>

        <div class="modal-body">
            {% include modal_body_url %}
        </div>

        <div class="modal-footer">
            {% if new_page_url %}
                <a  class="btn btn-default pull-left"
                    href="{{ new_page_url }}?new_page=yes"
                    target="_blank"
                    title="{% translate 'Open in new tab' %}">
                    <i class="far fa-window-restore"></i>
                </a>
            {% endif %}
            <button type="button" class="btn btn-default" data-dismiss="modal">
                {% translate 'Close' %}
            </button>
        </div>
    </div>
</div>

moonmining/templates/moonmining/modals/extraction_details.html
{% url 'moonmining:extraction_details' extraction.pk as new_page_url %}
{% include "moonmining/modals/content_base.html" with modal_content_id="modalExtractionDetailsContent" modal_body_url="moonmining/partials/extraction_details.html" modal_title="Extraction" new_page_url=new_page_url %}

moonmining/templates/moonmining/modals/extraction_ledger.html
<!-- {% url 'moonmining:extraction_ledger' extraction.pk as new_page_url %} -->
{% include "moonmining/modals/content_base.html" with modal_content_id="modalExtractionDetailsContent" modal_body_url="moonmining/partials/extraction_ledger.html" modal_title="Mining Ledger" new_page_url=False modal_size="modal-xl" %}

moonmining/templates/moonmining/modals/loader_body.html
<!-- The body of the loader modal. -->

{% load static %}

{% if NIGHT_MODE %}
    <img src="{% static 'moonmining/img/Spinner-1s-64px-dark.gif' %}"/>
{% else %}
    <img src="{% static 'moonmining/img/Spinner-1s-64px-light.gif' %}"/>
{% endif %}

moonmining/templates/moonmining/modals/moon_details.html
{% url "moonmining:moon_details" moon.pk as new_page_url %}
{% include "moonmining/modals/content_base.html" with modal_content_id="modalMoonDetailsContent" modal_body_url="moonmining/partials/moon_details.html" modal_title="Moon" new_page_url=new_page_url %}

moonmining/templates/moonmining/modals/upload_survey.html
{% include "moonmining/modals/content_base.html" with modal_content_id="modalUploadSurveyContent" modal_body_url="moonmining/partials/upload_survey.html" modal_title="Upload Survey" %}