moonmining/urls.py
"""Routes."""

from django.urls import path

from moonmining.views import extractions, moons, reports

from .views import general

app_name = "moonmining"

urlpatterns = [
    # general
    path("", general.index, name="index"),
    path("add_owner", general.add_owner, name="add_owner"),
    path("modal_loader_body", general.modal_loader_body, name="modal_loader_body"),
    path("tests", general.tests, name="tests"),
    # extractions
    path("extractions", extractions.extractions, name="extractions"),
    path(
        "extractions_data/<str:category>",
        extractions.extractions_data,
        name="extractions_data",
    ),
    path(
        "extraction/<int:extraction_pk>",
        extractions.extraction_details,
        name="extraction_details",
    ),
    path(
        "extraction_ledger/<int:extraction_pk>",
        extractions.extraction_ledger,
        name="extraction_ledger",
    ),
    # moons
    path("moons", moons.moons, name="moons"),
    path("upload_survey", moons.upload_survey, name="upload_survey"),
    path(
        "moons_data/<str:category>",
        moons.MoonListJson.as_view(),
        name="moons_data",
    ),
    path(
        "moons_fdd_data/<str:category>",
        moons.moons_fdd_data,
        name="moons_fdd_data",
    ),
    path("moon/<int:moon_pk>", moons.moon_details, name="moon_details"),
    # reports
    path("reports", reports.reports, name="reports"),
    path(
        "report_owned_value_data",
        reports.report_owned_value_data,
        name="report_owned_value_data",
    ),
    path(
        "report_user_mining_data",
        reports.report_user_mining_data,
        name="report_user_mining_data",
    ),
    path(
        "report_user_uploaded_data",
        reports.report_user_uploaded_data,
        name="report_user_uploaded_data",
    ),
    path(
        "report_ore_prices_data",
        reports.report_ore_prices_data,
        name="report_ore_prices_data",
    ),
]

moonmining/templates/moonmining/partials/extraction_details_head.html
{% load i18n %}
{% load humanize %}
{% load moonmining %}

<div class="row">
    <div class="col-md-6">
        {% include 'moonmining/partials/extraction_details_head_base.html' %}
    </div>

    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>{% translate 'Status:' %}</dt>
            <dd>{{ extraction.status_enum.bootstrap_tag_html }}</dd>

            <dt>{% translate 'Started:' %}</dt>
            <dd>
                <span title="{{ extraction.started_at|naturaltime }}">
                    {{ extraction.started_at|datetime }}
                </span>
                    by {{ extraction.started_by|default:"?" }}
            </dd>

            {% if extraction.status == extraction.Status.CANCELED %}
                <dt>{% translate 'Canceled:' %}</dt>
                <dd>
                    <span title="{{ extraction.canceled_at|naturaltime|default:'?' }}">
                        {{ extraction.canceled_at|datetime|default:"?" }}
                    </span> by {{ extraction.canceled_by|default:"?" }}
                </dd>
            {% endif %}

            <dt>{% translate 'Chunk arrival:' %}</dt>
            <dd>
                {% if extraction.status == extraction.Status.CANCELED %}<s>{% endif %}
                <span title="{{ extraction.chunk_arrival_at|naturaltime }}">
                    {{ extraction.chunk_arrival_at|datetime }}
                </span>
                {% if extraction.status == extraction.Status.CANCELED %}</s>{% endif %}
            </dd>

            <dt>{% translate 'Auto Fracture:' %}</dt>
            <dd>
                {% if extraction.status == extraction.Status.CANCELED %}<s>{% endif %}
                <span title="{{ extraction.auto_fracture_at|naturaltime }}">
                    {{ extraction.auto_fracture_at|datetime }}
                </span>
                {% if extraction.status == extraction.Status.CANCELED %}</s>{% endif %}
            </dd>

            <dt>{% translate 'Duration:' %}</dt>
            <dd>
                {% blocktranslate with duration_days=extraction.duration_in_days|floatformat %}{{ duration_days }} days{% endblocktranslate %}
            </dd>
        </dl>
    </div>
</div>

moonmining/templates/moonmining/partials/extraction_details_head_base.html
{% load i18n %}
{% load humanize %}
{% load moonmining %}

<dl class="dl-horizontal">
    <dt>{% translate 'Refinery:' %}</dt>
    <dd>{{ extraction.refinery.name }}</dd>

    <dt>{% translate 'Company:' %}</dt>
    <dd>{{ extraction.refinery.owner.name }}</dd>

    <dt>{% translate 'Moon:' %}</dt>
    <dd>{{ extraction.refinery.moon }}</dd>

    <dt>{% translate 'Location:' %}</dt>
    <dd>
        {% include "moonmining/partials/location.html" with eve_solar_system=extraction.refinery.moon.eve_moon.eve_planet.eve_solar_system %}
    </dd>

    <dt>{% translate 'Labels:' %}</dt>
    <dd>{{ extraction.refinery.moon.labels_html }}</dd>
</dl>

moonmining/templates/moonmining/partials/extraction_ledger_head.html
{% load i18n %}
{% load humanize %}
{% load moonmining %}

<div class="row">

    <div class="col-md-6">
        {% include 'moonmining/partials/extraction_details_head_base.html' %}
    </div>

    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>Chunk arrival:</dt>
            <dd>
                {% if extraction.status == extraction.Status.CANCELED %}<s>{% endif %}
                <span title="{{ extraction.chunk_arrival_at|naturaltime }}">
                    {{ extraction.chunk_arrival_at|datetime }}
                </span>
                {% if extraction.status == extraction.Status.CANCELED %}</s>{% endif %}
            </dd>

            <dt>{% translate 'Total mined volume:' %}</dt>
            <dd>
                {% blocktranslate with volume=total_volume|intword %}{{ volume }} m3{% endblocktranslate %}
            </dd>

            <dt>{% translate 'Total mined value:' %}</dt>
            <dd>
                {% blocktranslate with value=total_value|intword %}{{ value }} ISK{% endblocktranslate %}
            </dd>
        </dl>
    </div>

</div>

moonmining/templates/moonmining/partials/extraction_ledger_ledger.html
{% load i18n %}
{% load static %}
{% load humanize %}
{% load moonmining %}

<div class="table-responsive">
    {% if ledger|length > 0 %}
        <table class="table table-striped table-width-fix" id="table-ledger-ledger">
            <thead>
                <tr>
                    <th>{% translate 'Day' %}</th>
                    <th>{% translate 'Main' %}</th>
                    <th>{% translate 'Character' %}</th>
                    <th>{% translate 'Corporation' %}</th>
                    <th>{% translate 'Ore' %}</th>
                    <th class="text-right">{% translate 'Total Volume' %}</th>
                    <th class="text-right">{% translate 'Unit Price' %}</th>
                    <th class="text-right">{% translate 'Quantity' %}</th>
                    <th class="text-right">{% translate 'Total Price' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for record in ledger %}
                    <tr>
                        <td>{{ record.day }}</td>
                        <td>{{ record.user.profile.main_character.character_name }}</td>
                        <td>{{ record.character.name }}</td>
                        <td>{{ record.corporation.name }}</td>
                        <td>{{ record.ore_type.name }}</td>
                        <td class="text-right" data-order="{{ record.total_volume }}">
                            {{ record.total_volume|intcomma }}
                        </td>
                        <td class="text-right" data-order="{{ record.ore_type.extras.current_price }}">
                            {{ record.ore_type.extras.current_price|floatformat:"0"|intcomma }}
                        </td>
                        <td class="text-right" data-order="{{ record.quantity }}">
                            {{ record.quantity|intcomma }}
                        </td>
                        <td class="text-right" data-order="{{ record.total_price }}">
                            {{ record.total_price|formatisk:"m" }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr class="info">
                    <th>{% translate 'Total' %}</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th class="text-right">{{ total_volume|intcomma }}</th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right">{{ total_value|formatisk:"m" }}</th>
                </tr>
            </tfoot>
        </table>
    {% else %}
        <p class="text-muted">{% translate 'No data.' %}</p>
    {% endif %}
</div>

moonmining/templates/moonmining/partials/extractions_tab.html
{% load i18n %}
{% load humanize %}
{% load moonmining %}

<div role="tabpanel" class="tab-pane" id="tab_{{ category }}">
    <div class="table-responsive">
        <table class="table table-striped table-extractions table-width-fix" id="table_{{ category }}">
            <thead>
                <th>{% translate 'Chunk arrival' %}</th>
                <th>{% translate 'Refinery' %}</th>
                <th>{% translate 'Location' %}</th>
                <th>{% translate 'Labels' %}</th>
                <th class="text-nowrap text-right">{% translate 'Volume (m3)' %}</th>
                <th class="text-nowrap text-right">{% translate 'Est. Value' %}</th>
                <th class="text-nowrap text-right">{% translate 'Est. Mined' %}</th>
                <th></th>
            </thead>
            <tfoot>
                <th>{% translate 'Total' %}</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th class="text-nowrap text-right"></th>
                <th class="text-nowrap text-right"></th>
                <th class="text-nowrap text-right"></th>
            </tfoot>
        </table>
    </div>
</div>

moonmining/templates/moonmining/partials/location.html
{% load evelinks %}

{% if eve_solar_system %}
    <a href="{{ eve_solar_system.name|dotlan_solar_system_url }}" target="_blank">
        {{ eve_solar_system.name }}
    </a>
    {% with system=eve_solar_system %}
        <span class="{% if system.is_high_sec %}text-high-sec{% elif system.is_low_sec %}text-low-sec{% else %}text-null-sec{% endif%}">
            {{ system.security_status|floatformat:1 }}
        </span>
    {% endwith %}
    /
    {{ eve_solar_system.eve_constellation.name }}
    /
    {{ eve_solar_system.eve_constellation.eve_region.name }}
{% else %}
    <span class="text-muted">?</span>
{% endif %}

moonmining/templates/moonmining/partials/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% translate "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'moonmining:index' %}">{% translate "Moon Mining" %}</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if perms.moonmining.extractions_access %}
                    <li class="{% navactive request 'moonmining:extractions' %}">
                        <a href="{% url 'moonmining:extractions' %}">
                            {% translate 'Extractions' %}
                        </a>
                    </li>
                {% endif %}
                {% if "/moonmining/extraction/" in request.path %}
                    <li class="{% renavactive request '/moonmining/extraction/' %}">
                        <a href="#">{% translate 'Extraction Details' %}</a>
                    </li>
                {% endif %}
                <li class="{% navactive request 'moonmining:moons' %}">
                    <a href="{% url 'moonmining:moons' %}">{% translate 'Moons' %}</a>
                </li>
                {% if "/moonmining/moon/" in request.path %}
                    <li class="{% renavactive request '/moonmining/moon/' %}">
                        <a href="#">{% translate 'Moon Details' %}</a>
                    </li>
                {% endif %}
                 {% if perms.moonmining.reports_access %}
                    <li class="{% navactive request 'moonmining:reports' %}">
                        <a href="{% url 'moonmining:reports' %}">{% translate 'Reports' %}</a>
                    </li>
                {% endif %}
            </ul>

            {% if perms.moonmining.add_refinery_owner %}
                <a  class="btn btn-default navbar-btn"
                    style="float: right"
                    href="{% url 'moonmining:add_owner' %}">
                    {% translate 'Add Corporation' %}
                </a>
            {% endif %}
        </div>

    </div>
</nav>

moonmining/templates/moonmining/partials/moon_details_moon.html
{% load i18n %}
{% load moonmining %}

<div class="row">
    <div class="col-md-2">
        <p><strong>{% translate 'Name:' %}</strong></p>
    </div>
    <div class="col-md-10">
    <p>{{ moon.name }}&nbsp;</p>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <p><strong>{% translate 'Location:' %}</strong></p>
    </div>
    <div class="col-md-10">
        {% include "moonmining/partials/location.html" with eve_solar_system=moon.eve_moon.eve_planet.eve_solar_system %}
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <p><strong>{% translate 'Labels:' %}</strong></p>
    </div>
    <div class="col-md-10">
    <p>{{ moon.labels_html }}</p>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <p><strong>{% translate 'Refinery:' %}</strong></p>
    </div>
    <div class="col-md-10">
    {% if moon.refinery %}
        <p>{{ moon.refinery|default:"?" }}  / {{ moon.refinery.eve_type|default:"?" }}</p>
    {% else %}
        ?
    {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <p><strong>{% translate 'Corporation:' %}</strong></p>
    </div>
    <div class="col-md-10">
    <p>{{ moon.refinery.owner|default:"?" }}</p>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <p><strong>{% translate 'Est. Value:' %}</strong></p>
    </div>
    <div class="col-md-10">
    <p>{{ moon.value | formatisk }}</p>
    </div>
</div>

moonmining/templates/moonmining/partials/moon_details_products.html
{% load i18n %}
{% load humanize %}
{% load moonmining %}

{% if product_rows|length_is:"0" %}
    <p class="text-warning"><strong>
        {% translate 'There is no survey for this moon in the database.' %}
    </strong></p>
{% else %}

    {% for product in moon.products_sorted %}
        <div class="row">
            <div class="col-md-2">
                <img class="media-object" src="{{ product.ore_type.icon_url }}">
            </div>

            <div class="col-md-8">
                <p>
                    <a href="{{ product.ore_type.profile_url }}" target="_blank">{{ product.ore_type.name }}</a>
                    &nbsp;{{ product.ore_type.rarity_class.bootstrap_tag_html }}
                    &nbsp;{{ product.ore_type.extras.current_price|floatformat:"0"|intcomma|default:"?" }}
                    <small class="text-muted">{% translate 'ISK per unit' %}</small>
                </p>
                <div class="progress" style="height: 20px; width: 100%">
                    <div
                        class="progress-bar progress-bar-default progress-bar-striped"
                        role="progressbar"
                        aria-valuenow="{{ product.amount_percent }}"
                        aria-valuemin="0"
                        aria-valuemax="100"
                        style="width: {{ product.amount_percent }}%; line-height: 20px;"
                    >
                        <span class="sr-only">
                            {{ product.amount_percent|floatformat:"0" }}% {{ product.ore_type.name }}
                        </span>
                        <h5 class="media-heading" style="padding-top: 2px">
                            {{ product.amount_percent|floatformat:"0" }}%
                        </h5>
                    </div>
                </div>
            </div>

            <div class="col-md-2">
                <span class="pull-right">
                    <br>
                    {{ product.total_price|formatisk:"b" }}
                </span>
            </div>
        </div>
    {% endfor %}
{% endif %}
<p class="text-muted">
    {% if moon.products_updated_at %}
        {% translate 'Last updated at' %}
        {% translate "App" as estimated_by %}
        {% blocktranslate with updated_at=moon.products_updated_at|datetime|default:"?" updated_by=moon.products_updated_by.profile.main_character|default:estimated_by %}{{ updated_at }} by {{ updated_by }}{% endblocktranslate %}
    {% else %}
        {% translate 'Not yet updated' %}
    {% endif %}
<p>

moonmining/templates/moonmining/partials/moons_tab.html
{% load i18n %}
{% load bootstrap %}
{% load static %}

<div role="tabpanel" class="tab-pane" id="tab_{{ category }}">
    <div id="loader_{{ category }}">
        {% if NIGHT_MODE %}
            <img src="{% static 'moonmining/img/Spinner-1s-64px-dark.gif' %}" alt="Spinner"/>
        {% else %}
            <img src="{% static 'moonmining/img/Spinner-1s-64px-light.gif' %}" alt="Spinner"/>
        {% endif %}
    </div>

    <div id="wrapper_{{ category }}" style="display: none !important;">
        <div class="table-responsive">
            <table class="table table-striped table-moons table-width-fix" id="table_{{ category }}">
                <thead>
                    <th>{% translate 'Moon' %}</th>
                    <th>{% translate 'System' %}</th>
                    <th>{% translate 'Constellation' %}<br>{% translate 'Region' %}</th>
                    <th>{% translate 'Refinery' %}<br>{% translate 'Corporation' %}</th>
                    <th>{% translate 'Labels' %}</th>
                    <th class="text-nowrap text-right">{% translate 'Est. Value' %}</th>
                    <th></th>
                </thead>
            </table>
        </div>
    </div>
</div>

moonmining/templates/moonmining/partials/reports_owned_value_tab.html
{% load i18n %}

<div role="tabpanel" class="tab-pane active" id="tab_owned_value">
    <p class="report-title">
        {% translate 'Potential monthly income from owned moons by corporation' %}
    </p>
    <div class="table-responsive">
        <table class="table table-striped table-width-fix" id="table_owned_value">
            <thead>
                <th></th>
                <th>{% translate 'Corporation / Moon' %}</th>
                <th>{% translate 'Region' %}</th>
                <th>{% translate 'Rarity' %}</th>
                <th class="text-nowrap text-right">{% translate 'Est. Value' %}</th>
                <th class="text-nowrap text-right">{% translate '% of Grand Total' %}</th>
                <th class="text-nowrap text-right">{% translate 'Rank of Grand Total' %}</th>
                <th class="text-nowrap text-right">{% translate 'Total' %}</th>
            </thead>
            <tfoot>
                <th></th>
                <th class="info">{% translate 'Grand total' %}</th>
                <th class="info"></th>
                <th class="info"></th>
                <th class="info text-right"></th>
                <th class="info text-right"></th>
                <th class="info text-right"></th>
                <th class="info text-right"></th>
            </tfoot>
        </table>
    </div>
    {% include 'moonmining/partials/value_estimate_legend.html' %}
</div>

moonmining/templates/moonmining/partials/reports_user_mining_tab.html
{% load i18n %}
{% load humanize %}

<div role="tabpanel" class="tab-pane" id="tab_user_mining">
    <p class="report-title">
        {% translate 'Total mining of corporation moons by known mains per month' %}
    </p>
    <div class="table-responsive">
        <table class="table table-striped table-width-fix" id="table_user_mining">
            <thead>
                <tr>
                    <th>{% translate 'Name' %}</th>
                    <th>{% translate 'Corporation' %}</th>
                    <th>{% translate 'State' %}</th>
                    <th>{{ month_minus_3 }}<br>{% translate 'Volume' %}</th>
                    <th class="text-nowrap text-right">{{ month_minus_3 }}<br>{% translate 'Est. Value' %}</th>
                    <th class="text-nowrap text-right">{{ month_minus_2 }}<br>{% translate 'Volume' %}</th>
                    <th class="text-nowrap text-right">{{ month_minus_2 }}<br>{% translate 'Est. Value' %}</th>
                    <th class="text-nowrap text-right">{{ month_minus_1 }}<br>{% translate 'Volume' %}</th>
                    <th class="text-nowrap text-right">{{ month_minus_1 }}<br>{% translate 'Est. Value' %}</th>
                    <th class="text-nowrap text-right">{{ month_current }}<br>{% translate 'Volume' %}</th>
                    <th class="text-nowrap text-right">{{ month_current }}<br>{% translate 'Est. Value' %}</th>
                </tr>
            </thead>
            <tfoot>
                <th class="info">{% translate 'Grand Total' %}</th>
                <th class="info"></th>
                <th class="info"></th>
                <th class="info"></th>
                <th class="info text-right"></th>
                <th class="info text-right"></th>
                <th class="info text-right"></th>
                <th class="info text-right"></th>
                <th class="info text-right"></th>
                <th class="info text-right"></th>
                <th class="info text-right"></th>
            </tfoot>
        </table>
    </div>
    <p class="text-muted">
        {% blocktranslate with last_updated_at=ledger_last_updated|naturaltime|default:"?" %}Last update of mining ledgers at {{ last_updated_at }}{% endblocktranslate %}
    </p>
</div>

moonmining/templates/moonmining/partials/reports_user_uploaded_tab.html
{% load i18n %}
{% load humanize %}

<div role="tabpanel" class="tab-pane" id="tab_user_uploaded">
    <p class="report-title">{% translate 'Uploaded moons per main' %}</p>
    <div class="table-responsive">
        <table class="table table-striped table-width-fix" id="table_user_uploaded">
            <thead>
                <tr>
                    <th>{% translate 'Name' %}</th>
                    <th>{% translate 'Corporation' %}</th>
                    <th>{% translate 'State' %}</th>
                    <th class="text-nowrap text-right">{% translate 'Count' %}</th>
                </tr>
            </thead>
            <tfoot>
                <th class="info">{% translate 'Grand Total' %}</th>
                <th class="info"></th>
                <th class="info"></th>
                <th class="info text-right"></th>
            </tfoot>
        </table>
    </div>
</div>

moonmining/templates/moonmining/partials/upload_survey.html
{% load i18n %}

<p>{% translate 'Paste your moon scan results into the form below and click the submit button.' %}</p>

<form class="form-signin" role="form" action="{% url 'moonmining:upload_survey' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <textarea class="form-control" name="scan" rows="10" id="scan" required></textarea>
    </div>
    <br />
    <button class="btn btn-primary" type="submit" name="submit_scan" id="submit_scan">
        {% translate 'Submit Moon Scans' %}
    </button>
</form>